name: Check for updates
on:
  schedule: # for scheduling to work this file must be in the default branch
  - cron: "0 0 * * 1" # run weekly
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab

jobs:
  flatpak-external-data-checker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker://ghcr.io/flathub/flatpak-external-data-checker:latest
        env:
          GIT_AUTHOR_NAME: elementaryBot
          GIT_COMMITTER_NAME: elementaryBot
          GIT_AUTHOR_EMAIL: builds@elementary.io
          GIT_COMMITTER_EMAIL: builds@elementary.io
          EMAIL: builds@elementary.io
          GITHUB_TOKEN: ${{ secrets.GIT_USER_TOKEN }}
        with:
          args: --update --never-fork io.elementary.mail.json
